// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"context"
	v1 "hotgo/api/api/user/v1"
	"hotgo/internal/library/contexts"
	"hotgo/internal/model/input/appin"
	"hotgo/internal/service"

	"github.com/gogf/gf/v2/errors/gerror"
)

// User C端用户控制器
var User = cUser{}

type cUser struct{}

// Register 用户注册
func (c *cUser) Register(ctx context.Context, req *v1.RegisterReq) (res *v1.RegisterRes, err error) {
	userId, err := service.AppUser().Register(ctx, &appin.UserRegisterInp{
		Username: req.Username,
		Password: req.Password,
		Mobile:   req.Mobile,
		Email:    req.Email,
	})

	if err != nil {
		return
	}

	res = &v1.RegisterRes{
		UserId: userId,
	}
	return
}

// Login 用户登录
func (c *cUser) Login(ctx context.Context, req *v1.LoginReq) (res *v1.LoginRes, err error) {
	tokenString, user, err := service.AppUser().Login(ctx, &appin.UserLoginInp{
		Username: req.Username,
		Password: req.Password,
	})

	if err != nil {
		return
	}

	res = &v1.LoginRes{
		Token:     tokenString,
		ExpiresAt: user.UpdatedAt,
		UserInfo: v1.LoginUserInfo{
			Id:       user.Id,
			Username: user.Username,
			Nickname: user.Nickname,
			Avatar:   user.Avatar,
			Mobile:   user.Mobile,
			Email:    user.Email,
		},
	}
	return
}

// Info 获取用户信息
func (c *cUser) Info(ctx context.Context, req *v1.InfoReq) (res *v1.InfoRes, err error) {
	userId := contexts.GetUserId(ctx)
	if userId <= 0 {
		err = gerror.New("用户未登录")
		return
	}

	user, err := service.AppUser().GetUserInfo(ctx, userId)
	if err != nil {
		return
	}

	res = &v1.InfoRes{
		Id:          user.Id,
		Username:    user.Username,
		Nickname:    user.Nickname,
		Avatar:      user.Avatar,
		Mobile:      user.Mobile,
		Email:       user.Email,
		Sex:         user.Sex,
		Birthday:    user.Birthday,
		LastLoginAt: user.LastLoginAt,
		LastLoginIp: user.LastLoginIp,
		Status:      user.Status,
		CreatedAt:   user.CreatedAt,
		UpdatedAt:   user.UpdatedAt,
	}
	return
}

// Update 更新用户信息
func (c *cUser) Update(ctx context.Context, req *v1.UpdateReq) (res *v1.UpdateRes, err error) {
	userId := contexts.GetUserId(ctx)
	if userId <= 0 {
		err = gerror.New("用户未登录")
		return
	}

	err = service.AppUser().UpdateProfile(ctx, userId, &appin.UserUpdateProfileInp{
		Nickname: req.Nickname,
		Avatar:   req.Avatar,
		Sex:      req.Sex,
		Birthday: req.Birthday,
	})

	if err != nil {
		return
	}

	res = &v1.UpdateRes{}
	return
}
