// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"hotgo/internal/dao/internal"
)

// rECOVERYOURDATAInfoDao is the data access object for the table RECOVER_YOUR_DATA_info.
// You can define custom methods on it to extend its functionality as needed.
type rECOVERYOURDATAInfoDao struct {
	*internal.RECOVERYOURDATAInfoDao
}

var (
	// RECOVERYOURDATAInfo is a globally accessible object for table RECOVER_YOUR_DATA_info operations.
	RECOVERYOURDATAInfo = rECOVERYOURDATAInfoDao{internal.NewRECOVERYOURDATAInfoDao()}
)

// Add your custom methods and functionality below.
